version: "3.9"
volumes:
  db-store:
services:
  server:
    build:
      context: .
      dockerfile: ./infra/docker/server/Dockerfile
    volumes:
      - ./app/server:/opt/app
    ports:
      - ${SERVER_PUBLISHED_PORT}:80
    depends_on:
      - mysql
    tty: true
  mysql:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./infra/docker/mysql/Dockerfile
    ports:
      - ${DB_PUBLISHED_PORT}:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ="Asia/Tokyo"
