version: "3.9"
volumes:
  db-store:
services:
  server:
    build:
      context: .
      dockerfile: ./infra/docker/server/Dockerfile
    volumes:
      - ./app/server:/opt/app
    ports:
      - ${SERVER_PUBLISHED_PORT}:80
    depends_on:
      - pg
    tty: true
  pg:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./infra/docker/pg/Dockerfile
    ports:
      - ${DB_PUBLISHED_PORT}:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/app
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - TZ="Asia/Tokyo"
